# a workflow runs on release,setup bun,bun install,and then run bun bun-build.ts,then upload dist/build/* to release assets
name: Release on tags push
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun bun-build.ts exe ${{ github.ref }}
      # - uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allow_override: true
      #     files: >
      #         qmcli-windows-x64:dist/buildexe/qmcli-windows-x64/qmcli.exe
      #         qmcli-linux-x64:dist/buildexe/qmcli-linux-x64/qmcli
      #         qmcli-linux-arm64:dist/buildexe/qmcli-linux-arm64/qmcli
      #         qmcli-darwin-x64:dist/buildexe/qmcli-darwin-x64/qmcli
      #         qmcli-darwin-arm64:dist/buildexe/qmcli-darwin-arm64/qmcli
      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: "dist/build/*.zip"
          allowUpdates: true