# a workflow runs on release,setup bun,bun install,and then run bun bun-build.ts,then upload dist/build/* to release assets
name: Release on tags push
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun bun-build.ts exe
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          files: |
              dist/build/qmcli-windows-x64.zip
              dist/build/qmcli-linux-x64.zip
              dist/build/qmcli-linux-arm64.zip
              dist/build/qmcli-darwin-x64.zip
              dist/build/qmcli-darwin-arm64.zip