# a workflow runs on release,setup bun,bun install,and then run bun bun-build.ts,then upload dist/build/* to release assets
name: Release build exe
on:
  release:
    types:
      - edited
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun bun-build.ts exe
      - uses: cloudnode-pro/release-upload-asset@1.0.2
        with:
          # See the ‘Inputs’ section below for details.
          gh-token: ${{ github.token }}
          files: |
            dist/build/qmcli-windows-x64.zip
            dist/build/qmcli-linux-x64.zip
            dist/build/qmcli-linux-arm64.zip
            dist/build/qmcli-darwin-x64.zip
            dist/build/qmcli-darwin-arm64.zip