# a workflow runs on release,setup bun,bun install,and then run bun bun-build.ts,then upload dist/build/* to release assets
name: Release on tags push
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun bun-build.ts exe ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: "dist/build/*.zip"
          allowUpdates: true
          omitBody: true